import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

// Deterministic UI fixtures: no production data or server state is modified.
const out = new URL('../../.impeccable/review/', import.meta.url).pathname.replace(/^\/([A-Z]:)/i, '$1');
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const checks = [];
const user = { id:'visual-review', username:'Kiểm tra giao diện', email:'review@example.test', roles:['admin'], is_active:true };
const sample = 'Hôm nay b đã làm j r?';
const normalized = 'Hôm nay bạn đã làm gì rồi?';
for (const [name,width,height] of [['desktop',1440,960],['tablet',834,1112],['mobile',390,844]]) {
  const context = await browser.newContext({viewport:{width,height},reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write']});
  const page = await context.newPage();
  let mode='success'; let delay=0; const requests=[]; const errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.route('**/api/**',async route=>{
    const path = new URL(route.request().url()).pathname;
    let body={}; let status=200;
    if(path.endsWith('/auth/me')) body=user;
    else if(path.endsWith('/auth/login') || path.endsWith('/auth/register')) {
      await new Promise(r=>setTimeout(r,300)); status=401; body={detail:'Thông tin đăng nhập chưa đúng. Vui lòng thử lại.'};
    } else if(path.includes('/normalize/live')) {
      const req=route.request().postDataJSON(); requests.push(req);
      await new Promise(r=>setTimeout(r,delay));
      if(mode==='error'){status=503;body={detail:'Không thể kết nối dịch vụ chuẩn hóa. Vui lòng thử lại.'};}
      else body={inputText:req.text,inputVersion:req.inputVersion,normalizationPhase:'complete',primaryOutput:req.text===sample?normalized:req.text,variants:[],ambiguities:[],pendingSubmissions:[],warnings:[],errorTypes:[],latencyMs:18,semanticStatus:'not_needed',changes:req.text===sample?[{id:'b',kinds:['teencode'],originalStart:8,originalEnd:9,outputStart:8,outputEnd:11,originalText:'b',outputText:'bạn'}]:[]};
    } else if(path.includes('revision')) body={revision:1};
    else body=[];
    await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  });
  const capture=async file=>{await page.evaluate(()=>document.fonts.ready);if(!process.argv.includes('--no-screenshots')) await page.screenshot({path:`${out}/${file}.png`,fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${file}: horizontal overflow`);};
  await page.goto('http://localhost:5173/login');
  assert.equal(await page.locator('.auth-shell__frame').evaluate(e=>getComputedStyle(e).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  assert.equal(await page.locator('.auth-shell__frame').evaluate(e=>getComputedStyle(e).animationDuration),'0.4s');
  await page.emulateMedia({reducedMotion:'reduce'});
  await capture(`login-${name}`);
  await page.getByTestId('login-identifier').focus();
  assert.notEqual(await page.getByTestId('login-identifier').evaluate(e=>getComputedStyle(e).outlineStyle),'none');
  await page.keyboard.press('Tab'); assert(await page.getByTestId('login-password').evaluate(e=>e===document.activeElement));
  await page.getByTestId('login-password').fill('test-password');
  await page.getByRole('button',{name:'Hiện mật khẩu'}).click();
  assert.equal(await page.getByTestId('login-password').getAttribute('type'),'text');
  await page.getByTestId('login-identifier').fill('review');
  await page.getByTestId('login-submit').click();
  assert(await page.getByTestId('login-submit').isDisabled());
  await page.getByRole('alert').waitFor();
  assert.equal(await page.getByTestId('login-submit').isDisabled(),false);
  await capture(`login-error-${name}`);
  await page.getByRole('link',{name:'Đăng ký',exact:true}).click();
  await capture(`register-${name}`);
  await page.getByTestId('register-username').fill('review');
  await page.getByTestId('register-email').fill('review@example.test');
  await page.getByTestId('register-password').fill('test-password');
  await page.getByTestId('register-submit').click();
  assert(await page.getByTestId('register-submit').isDisabled());
  await page.getByRole('alert').waitFor();
  assert.equal(await page.getByTestId('register-submit').isDisabled(),false);
  await page.evaluate(u=>sessionStorage.setItem('viet-normalizer-session',JSON.stringify({token:'ui-fixture',user:u})),user);
  await page.goto('http://localhost:5173/');
  const editor=page.getByTestId('live-input-editor');await editor.waitFor();
  assert.equal(await page.getByRole('checkbox').isChecked(),false);
  assert.equal(await page.getByTestId('normalize-status').innerText(),'Chờ văn bản');
  await capture(`workspace-empty-${name}`);
  const before=await editor.boundingBox();
  delay=1200;await editor.fill(sample);
  await page.getByTestId('normalize-status').filter({hasText:'Đang xử lý'}).waitFor();
  await capture(`workspace-loading-${name}`);
  await page.getByTestId('primary-output').waitFor();
  assert.equal(await page.getByTestId('primary-output').innerText(),normalized);
  assert.equal((await editor.boundingBox()).y,before.y);
  await capture(`workspace-${name}`);
  await page.getByRole('button',{name:'Sao chép kết quả chuẩn hóa'}).click();
  await page.getByRole('button',{name:'Sao chép kết quả chuẩn hóa'}).filter({hasText:'Đã sao chép'}).waitFor();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),normalized);
  await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:()=>Promise.reject(new Error('Clipboard denied'))}));
  await page.getByRole('button',{name:'Sao chép kết quả chuẩn hóa'}).click();
  await page.getByRole('button',{name:'Sao chép kết quả chuẩn hóa'}).filter({hasText:'Thử lại'}).waitFor();
  await page.getByText('Thông tin về dữ liệu',{exact:true}).click();
  assert(await page.getByText(/ứng dụng không cam kết lưu trữ bằng 0/).isVisible());
  await page.getByText('Thông tin về dữ liệu',{exact:true}).click();
  delay=0;const long='Tiếng Việt: ă â ê ô ơ ư đ, hòa bình và rõ nghĩa.\n'.repeat(160);
  await editor.fill(long);await page.getByTestId('primary-output').filter({hasText:'hòa bình'}).waitFor();
  await page.getByTestId('primary-output').evaluate(e=>e.scrollTop=500);
  await editor.fill(long+'Thêm một câu.');
  await page.getByTestId('primary-output').filter({hasText:'Thêm một câu.'}).waitFor();
  assert.equal(await page.getByTestId('primary-output').evaluate(e=>e.scrollTop),500);
  await capture(`workspace-long-${name}`);
  mode='error';await editor.fill('Kiểm tra lỗi kết nối');await page.getByRole('alert').waitFor();
  await capture(`workspace-error-${name}`);
  assert.equal(errors.length,0,errors.join('\n'));
  assert(requests.every(r=>r.allowAI===false),'AI consent unexpectedly enabled');
  checks.push({viewport:name,width,height,passed:['auth form and password toggle','keyboard focus','login error','register layout','AI defaults off and disclosure','empty/loading/result/error','actual clipboard text','long text scroll retained','no horizontal overflow','no browser errors','reduced motion'],requests:requests.length});
  await context.close();
}
await browser.close();
await writeFile(`${out}/checks.json`,JSON.stringify({fixtures:true,checks},null,2));
console.log(JSON.stringify(checks,null,2));
